cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path("index", views.index, name="cart_index")
]

home_page/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from home_page import views

app_name = 'home-page'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    path('contact', views.contact, name="contact"),
    path('product-detail/<int:id>/',views.productDetail, name='product_detail'),
    path('blog', views.blog, name="blog"),
    path('blog-detail/<int:id>/', views.blogDetail, name="blog_detail"),
    path('shop/<int:cat_id>/<int:brand_id>/', views.shop, name="shop"),
    path('register', views.register, name="register"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout")
]

one_tech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from home_page import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home-page/', include('home_page.urls')),
    path('cart/', include("cart.urls")),
    path('orders/', include("orders.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home_page/models.py
from django.db import models
from email.policy import default
import datetime
from sympy.logic.boolalg import false

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 128, blank = False)
    description = models.TextField()
    
    def __str__(self):
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length = 128, blank = False)
    
    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    band = models.ForeignKey(Brand, on_delete=models.PROTECT)
    name = models.CharField(max_length = 128, blank = False)
    made_in = models.CharField(max_length = 64)
    description = models.TextField()
    price = models.FloatField()
    release_date = models.DateField()
    image = models.ImageField(upload_to = "images/", default = "")
    is_sale = models.BooleanField(default = False)
    is_feature = models.BooleanField(default = False)
    is_best_rate = models.BooleanField(default = False)
    is_deal_week = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length = 128, blank = False)
    content = models.TextField(blank = False)
    represent_image =  models.ImageField(upload_to = "images/", default = "")
    create_date = models.DateField(default = datetime.datetime.now())
    
    def __str__(self):
        return self.title
    
    
class Contact(models.Model):
    name = models.CharField(max_length = 64, blank = False)
    email = models.EmailField(max_length = 64, blank = False)
    phone_number = models.CharField(max_length = 32, blank = False)
    message = models.TextField(blank = False)
    create_date = models.DateField(default = datetime.datetime.now())

    def __str__(self):
        return self.name
    

        

home_page/forms.py
from django import forms
from home_page.models import Contact
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

class ContactForm(forms.ModelForm):
    name = forms.CharField(max_length=64, required=True)
    email = forms.EmailField(max_length=64, required=True)
    phone_number = forms.CharField(max_length=32, required=True)
    message = forms.Textarea(attrs={'required': True, 'row': 4, 'cols': 10})

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'placeholder': 'Your Name', 'class': 'contact_form_name input_field'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Your Email', 'class': 'contact_form_email input_field'})
        self.fields['phone_number'].widget.attrs.update({'placeholder': 'Enter Phone Number', 'class': 'contact_form_phone input_field'})
        self.fields['message'].widget.attrs.update({'placeholder': 'Input Some Message', 'class': 'text_field contact_form_message'})

    def setData(self, data):
        self.data = data
        self.is_bound = True

    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone_number', 'message']

class RegisterForm(forms.ModelForm):
    first_name = forms.CharField(max_length = 15, required = True)
    last_name = forms.CharField(max_length=15, required = True)
    email = forms.EmailField(max_length=64, required = True)
    username = forms.CharField(max_length=50, required = True)
    password = forms.CharField(widget=forms.PasswordInput())

    def setData(self, data):
        self.data = data
        self.is_bound = True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'placeholder': 'Enter First Name', 'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Enter Last Name', 'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Enter Email', 'class': 'form-control'})
        self.fields['username'].widget.attrs.update({'placeholder': 'Enter User Name', 'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'placeholder': 'Enter Password', 'class': 'form-control'})

    class Meta:
        model = User
        fields = ['first_name', 'last_name','username', 'email', 'password']

class LoginForm(forms.ModelForm):
    username = forms.CharField(max_length=50, required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    def setData(self, data):
        self.data = data
        self.is_bound = True

    def authenticate(self):
        user = authenticate(username=self.data['username'], password=self.data['password'])

        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder': 'Enter User Name', 'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'placeholder': 'Enter Password', 'class': 'form-control'})

    class Meta:
        model = User
        fields = ['username', 'password']

home_page/views.py
from django.shortcuts import render, redirect
from home_page.models import Product, Category, Blog, Brand
from cart.forms import CartAddProductForm
from home_page.forms import ContactForm, RegisterForm, LoginForm
from random import randint
from django.contrib.auth.password_validation import validate_password
from django.core import exceptions
import django.contrib.auth as auth
from django.db.models import Q

# Create your views here.
def index(request):
    products = []
    weekDealProduct = Product.objects.filter(is_deal_week = 1)
    featureProduct = Product.objects.filter(is_feature = 1)
    saleProduct = Product.objects.filter(is_sale = 1)
    bestRateProduct = Product.objects.filter(is_best_rate = 1)
    categories = Category.objects.all()

    return render(request, "home_page/index.html", {
                                                        "products": products,
                                                        "weekDealProduct" : weekDealProduct,
                                                        "featureProduct": featureProduct,
                                                        "saleProduct": saleProduct,
                                                        "bestRateProduct": bestRateProduct,
                                                        "categories": categories
                                                    })

def contact(request):
    contactForm = ContactForm()
    registered = False

    if request.method == "POST":
        contactForm.setData(request.POST)

        if contactForm.is_valid():
            register = contactForm.save()
            register.save()
            registered = True
        else:
            print(contactForm.errors)

    return render(request, "home_page/contact.html", {"contactForm" : contactForm, 'registered': registered})

def productDetail(request, id):
    product = Product.objects.get(id = id)
    cartProductForm = CartAddProductForm()
    
    return render(request, "home_page/product_detail.html", {
                                                                "product": product,
                                                                "cartProductForm": cartProductForm
                                                            }
                  
                  )
    
def blog(request):
    blogs = Blog.objects.all().order_by('-create_date')
    
    return render(request, "home_page/blog.html", {"blogs": blogs})

def blogDetail(request, id):
    random3Blog = []
    blog = Blog.objects.get(id = id)
    allBlogs = Blog.objects.all().values()
    totalBlogItem = len(allBlogs)
    maxBlogIndex = totalBlogItem - 1
    # Get ramdom three blog from all available blogs
    random3Blog.append(allBlogs[randint(0, maxBlogIndex)])
    random3Blog.append(allBlogs[randint(0, maxBlogIndex)])
    random3Blog.append(allBlogs[randint(0, maxBlogIndex)])

    return render(request, "home_page/blog_detail.html",{"blog": blog, "random3Blog": random3Blog})

def shop(request, cat_id = 0, brand_id = 0):
    category = None
    brands = Brand.objects.all()
    search = request.GET.get('search')

    if (cat_id):
        category = Category.objects.get(id = cat_id)
    if (brand_id == 0 and cat_id != 0):
        products = Product.objects.filter(category = cat_id)
    elif (cat_id != 0 and brand_id != 0):
        products = Product.objects.filter(category = cat_id, band = brand_id)
    elif (search is not None):
        products = Product.objects.filter(name__contains = search)
    else:
        products = Product.objects.all()

    return render(request, "home_page/shop.html", {'products': products, 'cat': category, 'brands': brands, 'cat_id': cat_id, 'brand_id': brand_id})

def register(request):
    registerForm = RegisterForm()
    registered = False

    if request.method == "POST":
        registerForm.setData(request.POST)

        if registerForm.is_valid():
            try:
                validate_password(registerForm.data['password'])
            except exceptions.ValidationError as e:
                registerForm.add_error('password', list(e.messages))

                return render(request, "home_page/register.html", {"registerForm": registerForm})
            user = registerForm.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(registerForm.errors)

    return render(request, "home_page/register.html", {"registerForm": registerForm, 'registered': registered})

def login(request):
    loginForm = LoginForm()

    if request.method == "POST":
        loginForm.setData(request.POST)
        user = loginForm.authenticate()

        if user:
                auth.login(request, user)

                return redirect("/")

    return render(request, "home_page/login.html", {"loginForm": loginForm})

def logout(request):
    auth.logout(request)

    return redirect("/")

templates/home_page/blog.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    <title>OneTech - Blog</title>
{% endblock %}

{% block extend_css %}
<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/blog_styles.css">
<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/blog_responsive.css">
{% endblock %}

{% block main_content %}
	<!-- Home -->

	<div class="home">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="{% static 'resource' %}/images/shop_background.jpg"></div>
		<div class="home_overlay"></div>
		<div class="home_content d-flex flex-column align-items-center justify-content-center">
			<h2 class="home_title">Technological Blog</h2>
		</div>
	</div>

	<!-- Blog -->

	<div class="blog">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="blog_posts d-flex flex-row align-items-start justify-content-between">
						<!-- Blog post -->
						{% for blog in blogs %}
							<div class="blog_post">
								<div class="blog_image" style="background-image:url({{ blog.represent_image.url }})"></div>
								<div class="blog_text">{{ blog.title }}</div>
								<div class="blog_button"><a href="{% url 'home-page:blog_detail' blog.id %}">Continue Reading</a></div>
							</div>
						{% endfor %}
					</div>
				</div>
					
			</div>
		</div>
	</div>
	
{% endblock %}
	
{% block extend_js %}
<script src="{% static "resource" %}/js/blog_custom.js"></script>
{% endblock %}

templates/home_page/blog_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    <title>Blog Post</title>
{% endblock %}

{% block extend_css %}
<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/blog_single_styles.css">
<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/blog_single_responsive.css">
{% endblock %}


{% block main_content %}

	<!-- Home -->

	<div class="home">
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="{{ blog.represent_image.url }}" data-speed="0.8"></div>
	</div>

	<!-- Single Blog Post -->

	<div class="single_post">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2">
					<div class="single_post_title">{{ blog.title }}</div>
					<div class="single_post_text">
						<p>
							{{ blog.content }}
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Blog Posts -->

	<div class="blog">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="blog_posts d-flex flex-row align-items-start justify-content-between">
						<!-- Blog post -->
						{% for blog in random3Blog %}
							<div class="blog_post">
								<div class="blog_image" style="background-image:url({% static "resource" %}/{{ blog.represent_image }})"></div>
								<div class="blog_text">{{ blog.title }}</div>
								<div class="blog_button"><a href="{% url 'home-page:blog_detail' blog.id %}">Continue Reading</a></div>
							</div>
						{% endfor %}

					</div>
				</div>	
			</div>
		</div>
	</div>
{% endblock %}
	
{% block extend_js %}
<script src="{% static "resource" %}/plugins/parallax-js-master/parallax.min.js"></script>
<script src="{% static "resource" %}/js/blog_single_custom.js"></script>
{% endblock %}

templates/home_page/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extend_css %}
	<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/contact_styles.css">
	<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/contact_responsive.css">
{% endblock %}

{% block main_content %}

	<!-- Contact Info -->

	<div class="contact_info">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 offset-lg-1">
					<div class="contact_info_container d-flex flex-lg-row flex-column justify-content-between align-items-between">

						<!-- Contact Item -->
						<div class="contact_info_item d-flex flex-row align-items-center justify-content-start">
							<div class="contact_info_image"><img src="{% static "resource" %}/images/contact_1.png" alt=""></div>
							<div class="contact_info_content">
								<div class="contact_info_title">Phone</div>
								<div class="contact_info_text">+38 068 005 3570</div>
							</div>
						</div>

						<!-- Contact Item -->
						<div class="contact_info_item d-flex flex-row align-items-center justify-content-start">
							<div class="contact_info_image"><img src="{% static "resource" %}/images/contact_2.png" alt=""></div>
							<div class="contact_info_content">
								<div class="contact_info_title">Email</div>
								<div class="contact_info_text">fastsales@gmail.com</div>
							</div>
						</div>

						<!-- Contact Item -->
						<div class="contact_info_item d-flex flex-row align-items-center justify-content-start">
							<div class="contact_info_image"><img src="{% static "resource" %}/images/contact_3.png" alt=""></div>
							<div class="contact_info_content">
								<div class="contact_info_title">Address</div>
								<div class="contact_info_text">10 Suffolk at Soho, London, UK</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Contact Form -->

	<div class="contact_form">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 offset-lg-1">
					<div class="contact_form_container">
						{% if registered %}
							<div class="alert alert-primary" role="alert">
  								Your message has been recorded. We will contact you soon.
							</div>
						{% else %}
							<div class="contact_form_title">Get in Touch</div>
							<form action="{% url 'home-page:contact' %}" id="contact_form" method="POST">
								{% csrf_token %}
								<div class="contact_form_inputs d-flex flex-md-row flex-column justify-content-between align-items-between">
									{{ contactForm.name }}
									{{ contactForm.email }}
									{{ contactForm.phone_number }}
								</div>
								<div class="contact_form_text">
									{{ contactForm.message }}
								</div>
								<div class="contact_form_button">
									<button type="submit" class="button contact_submit_button">Send Message</button>
								</div>
							</form>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		<div class="panel"></div>
	</div>

	<!-- Map -->

	<div class="contact_map">
		<div id="google_map" class="google_map">
			<div class="map_container">
				<div id="map"></div>
			</div>
		</div>
	</div>

{% endblock %}

{% block extend_js %}
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA"></script>
	<script src="{% static "resource" %}/js/contact_custom.js"></script>
{% endblock %}

templates/home_page/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extend_css %}
	<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/main_styles.css">
	<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/responsive.css">
{% endblock %}

{% block main_content %}
{% csrf_token %}
<!-- Banner -->
<div class="banner">
	<div class="banner_background"
		style="background-image: url({% static "resource" %}/images/banner_background.jpg)"></div>
	<div class="container fill_height">
		<div class="row fill_height">
			<div class="banner_product_image">
				<img src="{% static "resource" %}/images/banner_product.png" alt="">
			</div>
			<div class="col-lg-5 offset-lg-4 fill_height">
				<div class="banner_content">
					<h1 class="banner_text">new era of smartphones</h1>
					<div class="banner_price">
						<span>$530</span>$460
					</div>
					<div class="banner_product_name">Apple Iphone 6s</div>
					<div class="button banner_button">
						<!-- <a href="#">Shop Now</a>-->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Characteristics -->
<div class="characteristics">
			<div class="container">
				<div class="row">

					<!-- Char. Item -->
					<div class="col-lg-3 col-md-6 char_col">

						<div
							class="char_item d-flex flex-row align-items-center justify-content-start">
							<div class="char_icon">
								<img src="{% static "resource" %}/images/char_1.png" alt="">
							</div>
							<div class="char_content">
								<div class="char_title">Free Delivery</div>
								<div class="char_subtitle">Within order over $500</div>
							</div>
						</div>
					</div>

					<!-- Char. Item -->
					<div class="col-lg-3 col-md-6 char_col">

						<div
							class="char_item d-flex flex-row align-items-center justify-content-start">
							<div class="char_icon">
								<img src="{% static "resource" %}/images/char_2.png" alt="">
							</div>
							<div class="char_content">
								<div class="char_title">Free Test</div>
								<div class="char_subtitle">30 day from purchasing</div>
							</div>
						</div>
					</div>

					<!-- Char. Item -->
					<div class="col-lg-3 col-md-6 char_col">

						<div
							class="char_item d-flex flex-row align-items-center justify-content-start">
							<div class="char_icon">
								<img src="{% static "resource" %}/images/char_3.png" alt="">
							</div>
							<div class="char_content">
								<div class="char_title">Competitive Price</div>
								<div class="char_subtitle">Adjust price every week</div>
							</div>
						</div>
					</div>

					<!-- Char. Item -->
					<div class="col-lg-3 col-md-6 char_col">

						<div
							class="char_item d-flex flex-row align-items-center justify-content-start">
							<div class="char_icon">
								<img src="{% static "resource" %}/images/char_4.png" alt="">
							</div>
							<div class="char_content">
								<div class="char_title">24/7 Online Support</div>
								<div class="char_subtitle">By hotline, mail, skype</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Deals of the week -->
		<div class="deals_featured">
			<div class="container">
				<div class="row">
					<div
						class="col d-flex flex-lg-row flex-column align-items-center justify-content-start">

						<!-- Deals -->

						<div class="deals">
							<div class="deals_title">Deals of the Week</div>
							<div class="deals_slider_container">

								<!-- Deals Slider -->
								<div class="owl-carousel owl-theme deals_slider">

									<!-- Deals Item -->
									{% for product in weekDealProduct %}
									<div class="owl-item deals_item">
										<div class="deals_image">
											<img src="{{ product.image.url }}" alt="">
										</div>
										<div class="deals_content">
											<div
												class="deals_info_line d-flex flex-row justify-content-start">
												<div class="deals_item_category">
													<a href="#">{{ product.category.name }}</a>
												</div>
												<div class="deals_item_price_a ml-auto"></div>
											</div>
											<div
												class="deals_info_line d-flex flex-row justify-content-start">
												<div class="deals_item_name">
													<a href="{% url 'home-page:product_detail' product.id %}">{{ product.name }}</a>

												</div>
												<div class="deals_item_price ml-auto">{{ product.price }}</div>
											</div>
											<div class="available">
												<div
													class="available_line d-flex flex-row justify-content-start">
													<div class="available_title">
														Available: <span>6</span>
													</div>
													<div class="sold_title ml-auto">
														Already sold: <span>28</span>
													</div>
												</div>
												<div class="available_bar">
													<span style="width: 17%"></span>
												</div>
											</div>
											<div
												class="deals_timer d-flex flex-row align-items-center justify-content-start">
												<div class="deals_timer_title_container">
													<div class="deals_timer_title">Hurry Up</div>
													<div class="deals_timer_subtitle">Offer ends in:</div>
												</div>
												<div class="deals_timer_content ml-auto">
													<div class="deals_timer_box clearfix" data-target-time="">
														<div class="deals_timer_unit">
															<div id="deals_timer1_hr" class="deals_timer_hr"></div>
															<span>hours</span>
														</div>
														<div class="deals_timer_unit">
															<div id="deals_timer1_min" class="deals_timer_min"></div>
															<span>mins</span>
														</div>
														<div class="deals_timer_unit">
															<div id="deals_timer1_sec" class="deals_timer_sec"></div>
															<span>secs</span>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>

									{% endfor %}

								</div>

							</div>

							<div class="deals_slider_nav_container">
								<div class="deals_slider_prev deals_slider_nav">
									<i class="fas fa-chevron-left ml-auto"></i>
								</div>
								<div class="deals_slider_next deals_slider_nav">
									<i class="fas fa-chevron-right ml-auto"></i>
								</div>
							</div>
						</div>

						<!-- Featured -->
						<div class="featured">
							<div class="tabbed_container">
								<div class="tabs">
									<ul class="clearfix">
										<li class="active">Featured</li>
										<li>On Sale</li>
										<li>Best Rated</li>
									</ul>
									<div class="tabs_line">
										<span></span>
									</div>
								</div>

								<!-- Product Panel -->
								<div class="product_panel panel active">
									<div class="featured_slider slider">

										<!-- Slider Item -->
										{% for item in featureProduct %}
										<div class="featured_slider_item">
											<div class="border_active"></div>
											<div
												class="product_item discount d-flex flex-column align-items-center justify-content-center text-center">
												<div
													class="product_image d-flex flex-column align-items-center justify-content-center">
													<img src="{{ item.image.url }}" alt="" width="115px" height="115px">
												</div>
												<div class="product_content">
													<div class="product_price discount">
														{{ item.price }}
													</div>
													<div class="product_name">
														<div>
															<a href="{% url 'home-page:product_detail' item.id %}">{{ item.name }}</a>
														</div>
													</div>
													<div class="product_extras">
														<button class="product_cart_button" id="add_to_cart" data-url="{% url 'cart:cart_add' item.id %}">Add to Cart</button>
													</div>
												</div>
												<div class="product_fav">
													<i class="fas fa-heart"></i>
												</div>
												<ul class="product_marks">
													<li class="product_mark product_new">new</li>
												</ul>
											</div>
										</div>
										{% endfor %}

										
									</div>
									<div class="featured_slider_dots_cover"></div>
								</div>

								<!-- Product Panel -->

								<div class="product_panel panel">
									<div class="featured_slider slider">
										<!-- Slider Item -->
										{% for item in saleProduct %}
										<div class="featured_slider_item">
											<div class="border_active"></div>
											<div
												class="product_item discount d-flex flex-column align-items-center justify-content-center text-center">
												<div
													class="product_image d-flex flex-column align-items-center justify-content-center">
													<img src="{{ item.image.url }}" alt="" width="115px" height="115px">
												</div>
												<div class="product_content">
													<div class="product_price discount">
														{{ item.price }}
													</div>
													<div class="product_name">
														<div>
															<a href="{% url 'home-page:product_detail' item.id %}">{{ item.name }}</a>
														</div>
													</div>
													<div class="product_extras">
														<button class="product_cart_button" id="add_to_cart" data-url="{% url 'cart:cart_add' item.id %}">Add to Cart</button>
													</div>
												</div>
												<div class="product_fav">
													<i class="fas fa-heart"></i>
												</div>
												<ul class="product_marks">
													<li class="product_mark product_discount">-25%</li>
													<li class="product_mark product_new">new</li>
												</ul>
											</div>
										</div>
										{% endfor %}

									</div>
									<div class="featured_slider_dots_cover"></div>
								</div>

								<!-- Product Panel -->

								<div class="product_panel panel">
									<div class="featured_slider slider">
										<!-- Slider Item -->
										{% for item in bestRateProduct %}
										<div class="featured_slider_item">
											<div class="border_active"></div>
											<div
												class="product_item discount d-flex flex-column align-items-center justify-content-center text-center">
												<div
													class="product_image d-flex flex-column align-items-center justify-content-center">
													<img src="{{ item.image.url }}" alt="" width="115px" height="115px">
												</div>
												<div class="product_content">
													<div class="product_price discount">
														{{ item.price }}
													</div>
													<div class="product_name">
														<div>
															<a href="{% url 'home-page:product_detail' item.id %}">{{ item.name }}</a>
														</div>
													</div>
													<div class="product_extras">
														<button class="product_cart_button" id="add_to_cart" data-url="{% url 'cart:cart_add' item.id %}">Add to Cart</button>
													</div>
												</div>
												<div class="product_fav">
													<i class="fas fa-heart"></i>
												</div>
												<ul class="product_marks">
													<li class="product_mark product_new">new</li>
												</ul>
											</div>
										</div>
										{% endfor %}


									</div>
									<div class="featured_slider_dots_cover"></div>
								</div>

							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
{% endblock %}

{% block extend_js %}
	<script src="{% static "resource" %}/js/custom.js"></script>
{% endblock %}