cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path("index", views.index, name="cart_index")
]

one_tech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from home_page import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home-page/', include('home_page.urls')),
    path('cart/', include("cart.urls")),
    path('orders/', include("orders.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]

class CartAddProductForm(forms.Form):
    #quantity = forms.ChoiceField(choices=PRODUCT_QUANTITY_CHOICES, widget=forms.Select(attrs={'class':'form-control','style':'width: 90px; text-align:center'}))
    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={'type': 'text', 'id': 'quantity', "pattern":"[0-9]*", "value": "1", "class":"form-control"}))

    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from home_page.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.http import JsonResponse
from sympy.logic.boolalg import false


@require_POST
def cart_add(request, product_id):
	
	cart = Cart(request)  # create a new cart object passing it the request object 
	product = get_object_or_404(Product, id=product_id) 
	result = {
		"success": True,
		"total_item": 0,
		'total_item': 0,
		'error': ""
	}
	if 'price' not in request.POST:
		price=0
	else:
		price=request.POST['price']
	print("------------------------------",product.price)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, price=product.price, quantity=int(cd['quantity']), update_quantity=cd['update'])
		result['total_item'] = len(cart)
		result['total_price'] = cart.get_total_price()
	else:
		result['error'] = form.errors()
		result['success'] = False
		
	return JsonResponse(result)


def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')


def cart_detail(request):
	print('------------------------------------')
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
		print(item['update_quantity_form'])
	return render(request, 'cart/detail.html', {'cart': cart})

def index(request):
	
	return render(request, "cart/index.html")

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    <title>OneTech - Your Cart</title>
{% endblock %}

{% block extend_css %}
	<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/contact_styles.css">
	<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/contact_responsive.css">
{% endblock %}

{% block main_content %}

    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2><span class="badge pull-right">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}">
                            <span id="total_item">{{ total_items }}</span> item, $ <span class="total_price">{{ cart.get_total_price }}</span>
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover" id="cart">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'resource/images/default.png' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form class="form-inline" action="{% url "cart:cart_add" product.id %}" data-price="{{ item.price }}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}

                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>$ {{ item.price }}</td>
                            <td>$ <span class="item_price">{{ item.total_price }}</span></td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>$ <span class="total_price">{{ cart.get_total_price }}</span></b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right" style="width:100%">
                <a href="{% url "orders:order_create" %}" class="btn btn-primary float-right">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}

{% block extend_js %}
	<script src="{% static "resource" %}/js/cart_custom.js"></script>
{% endblock %}

cart/templates/cart/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    <title>OneTech - Your Shopping Cart</title>
{% endblock %}

{% block main_css %}
	<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/product_styles.css">
	<link rel="stylesheet" type="text/css" href="{% static "resource" %}/styles/product_responsive.css">
{% endblock %}



{% block main_content %}

   <h1>Hello</h1>
{% endblock %}

{% block main_js %}
	<script src="{% static "resource" %}/js/product_custom.js"></script>
{% endblock %}