cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path("index", views.index, name="cart_index")
]

home_page/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from home_page import views

app_name = 'home-page'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    path('contact', views.contact, name="contact"),
    path('product-detail/<int:id>/',views.productDetail, name='product_detail'),
    path('blog', views.blog, name="blog"),
    path('blog-detail/<int:id>/', views.blogDetail, name="blog_detail"),
    path('shop/<int:cat_id>/<int:brand_id>/', views.shop, name="shop"),
    path('register', views.register, name="register"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout")
]

one_tech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from home_page import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('home-page/', include('home_page.urls')),
    path('cart/', include("cart.urls")),
    path('orders/', include("orders.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/nav.html
<nav class="main_nav">
				<div class="container">
					<div class="row">
						<div class="col">

							<div class="main_nav_content d-flex flex-row">

								<!-- Categories Menu -->

								<div class="cat_menu_container">
									<div
										class="cat_menu_title d-flex flex-row align-items-center justify-content-start">
										<div class="cat_burger">
											<span></span><span></span><span></span>
										</div>
										<div class="cat_menu_text">categories</div>
									</div>

									<ul class="cat_menu">
										{% for cat in category %}
											<li><a href="{% url 'home-page:shop' cat.id 0 %}">{{ cat.name }}
												<i class="fas fa-chevron-right ml-auto"></i></a>
											</li> 
										{% endfor %}
									</ul>
								</div>

								<!-- Main Nav Menu -->

								<div class="main_nav_menu ml-auto">
									<ul class="standard_dropdown main_nav_dropdown">
										<li><a href="{% url 'home-page:index' %}">Home<i class="fas fa-chevron-down"></i></a></li>
										<li><a href="{% url 'home-page:shop' 0 0 %}">Shop<i class="fas fa-chevron-down"></i></a></li>
										<li><a href="{% url 'home-page:blog' %}">Blog<i class="fas fa-chevron-down"></i></a></li>
										<li><a href="{% url 'home-page:contact' %}">Contact<i class="fas fa-chevron-down"></i></a></li>
									</ul>
								</div>

								<!-- Menu Trigger -->

								<div class="menu_trigger_container ml-auto">
									<div
										class="menu_trigger d-flex flex-row align-items-center justify-content-end">
										<div class="menu_burger">
											<div class="menu_trigger_text">menu</div>
											<div class="cat_burger menu_burger_inner">
												<span></span><span></span><span></span>
											</div>
										</div>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</nav>